version: 2.1

jobs:
  Gosec:
    docker:
      - image: cimg/go:1.24.0
    steps:
      - checkout
      - run:
          name: Install gosec
          command: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run:
          name: Run gosec
          command: |
            export PATH=$PATH:$(go env GOPATH)/bin
            gosec -exclude-dir=internal/adapters/grpc ./...

  Lint:
    docker:
      - image: cimg/go:1.24.0
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - run:
          name: Run golangci-lint
          command: |
            export PATH=$PATH:$(go env GOPATH)/bin
            golangci-lint run --timeout=5m

  Unit-test:
    docker:
      - image: "cimg/go:1.24.0"
    steps:
      - checkout
      - run:
          name: Unit test
          command: go test ./...

  Build-and-deploy:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run:
          name: Docker build and deploy
          command: |
            echo "$GITLABPASSWORD" | docker login registry.gitlab.com --username acnologla --password-stdin
            docker buildx build --platform linux/arm64/v8 --tag registry.gitlab.com/acnologla/asuratrade --push .

workflows:
  version: 2
  test_and_build:
    jobs:
      - Gosec
      - Lint
      - Unit-test:
          requires:
            - Gosec
            - Lint
      - Build-and-deploy:
          requires:
            - Unit-test
          filters:
            branches:
              only: main
